# @package agent
_target_: agent.diayn.DIAYNDreamerAgent
name: diayn_dreamer
cfg: ???
obs_space: ???
act_spec: ???
grad_heads: [decoder]
reward_norm: {momentum: 0.95, scale: 1.0, eps: 1e-8}
actor_ent: 0.1

diayn_scale: 1.0
update_skill_every_step: 50

skill_reward_norm: {momentum: 0.95, scale: 1.0, eps: 1e-8} 
skill_actor_ent: 0.1
skill_dim: 50

num_init_frames: 4000

reward_type: 0
