# @package agent
_target_: agent.peac_diayn.PEACDIAYNAgent
name: peac_diayn
cfg: ???
obs_space: ???
act_spec: ???
grad_heads: [decoder]
reward_norm: {momentum: 1.0, scale: 1.0, eps: 1e-8}
actor_ent: 1e-4

diayn_scale: 1.0
update_skill_every_step: 50
task_scale: 1.0

context_skill_reward_norm: {momentum: 0.95, scale: 1.0, eps: 1e-8}
context_skill_actor_ent: 0.1
skill_dim: 50
diayn_hidden: 50

num_init_frames: 4000

freeze_skills: False

task_number: 1