# @package agent
_target_: agent.random_dreamer.RandomDreamerAgent
name: random_dreamer
cfg: ???
obs_space: ???
act_spec: ???
grad_heads: [decoder]
reward_norm: {momentum: 1.0, scale: 1.0, eps: 1e-8}
actor_ent: 1e-4