# @package agent
_target_: agent.rnd.RNDDreamerAgent
name: rnd_dreamer
cfg: ???
obs_space: ???
act_spec: ???
grad_heads: [decoder]
reward_norm: {momentum: 1.0, scale: 1.0, eps: 1e-8}
actor_ent: 0 

rnd_scale: 1.0
rnd_rep_dim: 512