obs_type: states
action_repeat: 1
encoder: {mlp_keys: 'observation', cnn_keys: '$^', norm: layer, cnn_depth: 48, cnn_kernels: [4, 4, 4, 4], mlp_layers: [400, 400, 400, 400]}
decoder: {mlp_keys: 'observation', cnn_keys: '$^', norm: layer, cnn_depth: 48, cnn_kernels: [5, 5, 6, 6], mlp_layers: [400, 400, 400, 400]}
replay.capacity: 2e6